version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: test_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  microserviceb-container:
    image: duwansierra/microserviceb:latest
    ports:
      - 8081:8081
    depends_on:
      - mongodb_container
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb_container:27017/test_db
volumes:
  mongodb_data_container: