version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: test_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  mongoclient:
      image: mongoclient/mongoclient:latest
      container_name: mongoclient
      hostname: mongoclient
      depends_on:
        - mongodb_container
      ports:
        - 3300:3000
volumes:
  mongodb_data_container: